---
# yaml-language-server: $schema=https://kubernetes-schemas-ebx.pages.dev/talos.dev/serviceaccount_v1alpha1.json
apiVersion: talos.dev/v1alpha1
kind: ServiceAccount
metadata:
  name: home-ops-runner
  namespace: actions-runner
spec:
  roles:
    - os:admin
