---
cluster_name: "home-ops"
cluster_api_addr: "{{ lookup('community.general.onepassword', 'cluster-network', field='CLUSTER_API_IP') }}"
cluster_endpoint: "https://{{ cluster_api_addr }}:6443"
cluster_gateway_internal: "{{ lookup('community.general.onepassword', 'cluster-network', field='CLUSTER_GATEWAY_INTERNAL_IP') }}"
nas_ip: "{{ lookup('community.general.onepassword', 'cluster-network', field='NAS_IP') }}"
node01_ip: "{{ lookup('community.general.onepassword', 'cluster-network', field='NODE_IP_1') }}"
node02_ip: "{{ lookup('community.general.onepassword', 'cluster-network', field='NODE_IP_2') }}"
node03_ip: "{{ lookup('community.general.onepassword', 'cluster-network', field='NODE_IP_3') }}"
talos_config_dir: "{{ playbook_dir }}/../../talos/clusterconfig"
github_repo: "thomloy/home-ops"
github_branch: "main"
cloudflare_domain: "{{ lookup('community.general.onepassword', 'cluster-network', field='SECRET_DOMAIN') }}"
