---
# yaml-language-server: $schema=https://kubernetes-schemas-ebx.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: qbittorrent-secret
    template:
      data:
        QBT_WEBUI_USERNAME: "{{ .username }}"
        QBT_WEBUI_PASSWORD: "{{ .password }}"
  dataFrom:
    - extract:
        key: qbittorrent
