---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-gateway
spec:
  chartRef:
    kind: OCIRepository
    name: k8s-gateway
  interval: 1h
  values:
    fullnameOverride: k8s-gateway
    domain: "kryzql.space"
    ttl: 1
    extraArgs:
      - --exclude-domains=_acme-challenge.kryzql.space
    service:
      type: LoadBalancer
      port: 53
      annotations:
        lbipam.cilium.io/ips: "192.168.42.99"
      externalTrafficPolicy: Cluster
    watchedResources: ["HTTPRoute", "Service"]
