---
# yaml-language-server: $schema=https://kubernetes-schemas-ebx.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: ${SECRET_DOMAIN_SLUG}-tls
  namespace: network
spec:
  secretStoreRefs:
    - name: onepassword
      kind: ClusterSecretStore
  selector:
    secret:
      name: ${SECRET_DOMAIN_SLUG}-tls
  template:
    type: kubernetes.io/tls
    data:
      tls.crt: '{{ index . "tls.crt" | b64dec }}'
      tls.key: '{{ index . "tls.key" | b64dec }}'
  data:
    - match:
        secretKey: &key tls.crt
        remoteRef:
          remoteKey: ${SECRET_DOMAIN_SLUG}-tls
          property: *key
    - match:
        secretKey: &key tls.key
        remoteRef:
          remoteKey: ${SECRET_DOMAIN_SLUG}-tls
          property: *key
