---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bentopdf
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: bentopdf
  values:
    controllers:
      bentopdf:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/alam00000/bentopdf-simple
              tag: 2.8.2@sha256:d59a3812cb98c4887672ea73425722ee3dd7010969736c974c6b4ce7ba32c4fb
            env:
              TZ: Europe/Paris
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi
    defaultPodOptions:
      securityContext: {}
    service:
      app:
        ports:
          http:
            port: 8080
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |-
            alerts:
              - type: pushover
            ui:
              hide-hostname: true
        hostnames:
          - pdf.${SECRET_DOMAIN}
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      nginx-cache:
        type: emptyDir
        globalMounts:
          - path: /var/cache/nginx
      nginx-tmp:
        type: emptyDir
        globalMounts:
          - path: /var/lib/nginx/tmp
      nginx-logs:
        type: emptyDir
        globalMounts:
          - path: /var/lib/nginx/logs