---
ansible_host: "{{ lookup('community.general.onepassword', 'cluster-network', field='NODE_IP_1') }}"
talos_mac: "{{ lookup('community.general.onepassword', 'cluster-network', field='NODE01_MAC') }}"
