---
ansible_host: "{{ lookup('community.general.onepassword', 'cluster-network', field='NODE_IP_2') }}"
talos_mac: "{{ lookup('community.general.onepassword', 'cluster-network', field='NODE02_MAC') }}"
