apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:lFRi6hgrhL+v1Ta8u+FkgCLMLTrgS1QvjCi6rfIq+ui6SGBQRzIglQ==,iv:bRSMzJJlTbb+CG0FWuOqS9/O8ohSzUoi18UORj9yJHo=,tag:M9Ckz7AJfI+XkqlxDZlH4Q==,type:str]
sops:
  age:
    - recipient: age1ctpw7mxxzshknqmtwfn9c202hx0j57tv29fdsx4hym6hm5ed2stqtft3he
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4N1VzVzljMndXRk9iZXdH
        K1J6SjBsTUJTWDVJWVBSSVNHS0JxNGllenc4CjlQTmlWQkc0dEM4OU9sTkx4QnVS
        c21WeFBIdE8zTDM3OThOZmdMaFR6aTAKLS0tIHd6T2JsemU0NGZOL0kvdERTaXpF
        RXA4UlJqeWYwaE93UjdzMkU0N1c1ZXcKK7AmO4sGbruX7tPAcahO8IRkUIGQg+D2
        ucL86+8BDkldx3/L3Q2vRuq1skhvdsYyt/ZvNQ4GtSYOAMwptSvDMQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-31T16:43:32Z"
  mac: ENC[AES256_GCM,data:xnANAiyMjh7x8yNEzbTeL1i/z3d8B8z+9LxbHI+IsF5vFw9uq5rmqMoIlF9ldV9lFQMtEk3YFnDzRFPqqLV0Lv75FUgCUvDcZeQJJBw/wKTFNNmFp+u3158HcH3ha74Wwa8IaBlZ/G2YcF99YicsLO4C4O+KM+38ynA4jSjrZi0=,iv:NwIFUxHvtL5SajwIDy4QAkPNyWuOt4dHaERhZ/GcJVQ=,tag:fX0Flt1jZoYnjGUhgRjMbg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
