apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:fyShFB/Mo4/qUE381g2KcNsH+/fD81BVhiPdlfeiav9uXTuJqIEjmA==,iv:abMnsAmY0YsOHrTuS5nkPJKp8hNtg7GY8jrgEFeJDgg=,tag:y2llNBNhQ6m2dB9PGktGGQ==,type:str]
sops:
  age:
    - recipient: age1ctpw7mxxzshknqmtwfn9c202hx0j57tv29fdsx4hym6hm5ed2stqtft3he
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0b1VUc2NrRWE2V2pRTER5
        b1BqYnlreW5WbUxIYWJENUgxUy9iNWFVUVRZClZqNDdIRnJsKzdnaFYwSmx0c3py
        L0V2dzRVTldOTFNSSE1aZEFoSFAza28KLS0tIHpPemJMVkZZV285bzJXcUwvNkNF
        dmpCZk9UWWdmRlJ3RFpxKzJZbXJ2eWcKi4EUXsEJHggmlTtkS4Z7RXiexO6o1gN/
        8WuCGaV3l8N96ly9AJ2DJU0rJ4FfYGGHZPuGG7MquTFOKHgn21rY0g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-05T00:08:25Z"
  mac: ENC[AES256_GCM,data:vkDA7a+ePT2x8ek4QW3LdxsEuQtZNN7r1bpOscs5U04sd+UAOJLWuw9OE7Y50FDG6ysu33/0Npb9ls50Z9R1MR2K7ofXMrPUgPDKZ3bJeALtBbHMUrniTid5AUReudjqreolOYvyqaK4hlQ4720lvKCk1UDpMHUwE/h+xni72/I=,iv:anqeYyoer9eij5JBoZ/XoWhly6fdWkBQ0lG4YXSsLOc=,tag:8JwNvlEsSf8yg0BQl2K2Og==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
