apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:bRTcsCxr5RsXSkF/tJynpXMiQEsrYnJ7lChzWns9IlM0bPXZ0A8UPQ==,iv:3PuFAuRFC/fLYlvhvsKRShPS5g4Z/hRktQzlE48wUkw=,tag:N2lGJQKaSI19CDjOvL2odw==,type:str]
sops:
  age:
    - recipient: age1ctpw7mxxzshknqmtwfn9c202hx0j57tv29fdsx4hym6hm5ed2stqtft3he
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyUUg2Q08rRUp0ZnMxVWw0
        eTFTT3BwL0l2cHRta1NUdnFiSkJpZHVoSjE0CllMS0ZrWlltbXUzVkkwbnp3TUFj
        VFNVL29La3c2RGo1OHJCbmM1L3JWME0KLS0tIGJBN3BhdEFJeGRxUEVQbHArU3Vs
        YU9aWWZ6djIxeDdzNm9VdWUzV1BXb2MKPRomxXxvq2KTcp0krP6t/DNDah7FwJVs
        6lftAoLJAavXI1gEkrfn/AdxWU13z20INN1t3Lib+3StVYaiMxE0bg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-31T16:22:28Z"
  mac: ENC[AES256_GCM,data:qFcNwiK/o0o04MjCQ8zgXaZzOSF4bj+Ns1hLV4djCzak05jYvquUh3jrqHE5a2HjwepcxY6mIn810OApnEdHCAZ0N5Fp8/kF8Yc5kbh6regvxKxjoN8S6rVYo5BhX0XuVGykl8jxcxyYReW2U3McLTil6Qt0d19maxpP2gsh3qA=,iv:ie0Fmgr7lDrR7CGDR47lRcKXTsM+LiHCxhEkjzAPl/Q=,tag:NYMB4R7geVNklkyh0S656g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
