apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: graphite-exporter
  namespace: observability
spec:
  chartRef:
    kind: OCIRepository
    name: graphite-exporter
  interval: 1h
  values:
    controllers:
      main:
        replicas: 1
        containers:
          main:
            image:
              repository: prom/graphite-exporter
              tag: v0.16.0
            args:
              - "--graphite.listen-address=:2003"
              - "--web.listen-address=:9108"
    config:
      mapping:
        mappings:
          - match: "truenas.nas.ups.*"
            name: "ups"
            labels:
              source: "truenas"
    service:
      main:
        controller: main
        ports:
          graphite:
            port: 2003
          metrics:
            port: 9108
    serviceMonitor:
      main:
        enabled: true
        serviceName: graphite-exporter
        endpoints:
          - port: metrics
            interval: 30s