apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: graphite-exporter
  namespace: observability
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: graphite-exporter

  values:
    controllers:
      main:
        replicas: 1
        containers:
          main:
            image:
              repository: prom/graphite-exporter
              tag: v0.16.0
            args:
              - "--graphite.listen-address=:2003"
              - "--web.listen-address=:9108"

    service:
      main:
        controller: main
        ports:
          graphite:
            port: 2003
          metrics:
            port: 9108
      lb:
        controller: main
        type: LoadBalancer
        ports:
          graphite:
            port: 2003

    serviceMonitor:
      main:
        enabled: true
        endpoints:
          - port: metrics
            interval: 30s
