---
# yaml-language-server: $schema=https://kubernetes-schemas-ebx.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sparkyfitness-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: sparkyfitness-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: sparkyfitness
        property: POSTGRES_PASSWORD
    - secretKey: APP_DB_PASSWORD
      remoteRef:
        key: sparkyfitness
        property: APP_DB_PASSWORD
    - secretKey: API_ENCRYPTION_KEY
      remoteRef:
        key: sparkyfitness
        property: API_ENCRYPTION_KEY
    - secretKey: BETTER_AUTH_SECRET
      remoteRef:
        key: sparkyfitness
        property: BETTER_AUTH_SECRET
