apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:axDKWQjFV2mtOdHO,iv:GhkokmhTwunQl1TQKmV2i09P9dy1cdHfDrf6NFb2cyA=,tag:TT8MVz93vNa08afQ3dTY0Q==,type:str]
sops:
  age:
    - recipient: age1hrnksegh2ng9csun3twlvj936x95x4a4ca09p23xvwmzdyz7w5sq7nmr4l
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRXRuK2E4WWczWXo2Rk8y
        R3lNbEtuZEtsaytxemVab2F2ZHFoY0lrdFEwCmNFSm41STBEckRTZG5TMjcyUkRL
        VUdueGdEVkJVK2x0TGEwWnJjc0d0cjgKLS0tIFdKSEFwOWZvTFZ4UG0wZCtmc0Ur
        SE5ic085NExscUJFTFByNXRCeXRTQVUKOUBZQvSRzyx/t1GX3JlcIQj+KFhgNxpg
        +UhY0xCNr6iAoG2xa4yYuzJA9Zqh4CnpGh7Vk7dKkZQx4grpbYPNsA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-26T12:26:40Z"
  mac: ENC[AES256_GCM,data:2/dAjNc0h0TzlGo3wPyEuVlxlm+FpGRkzjWobQaHzrMgiPymzZB3FQaCm6e0+HHSYvhJdAw0a8pfcBsGDiiNNIh9slvtKjB0HMg0ostGj30fkGojQF6tVE2ZDVtALjTkN+5FSPasQtbbqVS9JAxBmaQKj833Q4E3QnYkKoptMVI=,iv:/QXfxxAzhgNdvqChDLYB2ELBr4dTBZh3MUbun0j36A4=,tag:MUXfGS3SM7dnsnOG/a6Fig==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
