apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:tNdVWQH/6HDWVWuu,iv:5I7DVHWt6+tak1LJP/XXMoBapVtNL0/O2fx3GMXj3bc=,tag:lc0NZlAIwTdT+tt5vWwizg==,type:str]
sops:
  age:
    - recipient: age1ctpw7mxxzshknqmtwfn9c202hx0j57tv29fdsx4hym6hm5ed2stqtft3he
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPOVZIS21SZzRyRk16U0hJ
        Vi9ES1Q2elJRMlRPNjhuRjFwRnlQbUNGaVNRCm1kOEN4SldYNkg2WDhCR2xLdWFJ
        WUxRTmwwWENrMUNXZG9lOTlqRGF1V2sKLS0tIHl6a0I3SisrM3JhVVJFVEZZQ0gz
        ZklPNFpoeUJJV0pqMDRyTERoV3VsdkkKMRA1wC3sJCb99KjcNrJnU01UJqZQcbGQ
        Mc8CImiujVRoAQoTqfHJUx7SBcRX61USYYtoO3SZFVEVxQAECKGlhQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-05T00:08:25Z"
  mac: ENC[AES256_GCM,data:K2nCnkoOkjcsiZ90cfNokjgJOLyVs6I1VgB4SuEEJs5MWUhpgYopZlKTm2AsvpRzx1Duk/Om3XukWRPghamBYYVst86ybv+ZU61aPKpyRYKy4zKjJ6mrv2Fbr7tae2sRbFz4CmFa4TFDyYCze05mT9s0ApG4ins9ZHLLn1AwbCc=,iv:MKfrDGYRt5dEDIQOavTPCN9vBzhaunSbDw91V5LVjck=,tag:eRD9ZrnfXLY4Gvx9H2OJrw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
