apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  BGP_ROUTER_IP: ENC[AES256_GCM,data:6CYMil0Sv3YZpceH,iv:6G1kgzDgSDyImAT3c5b52QBI1f1Pr/aIcpLTAN8g2Ms=,tag:GO3mjA/RR7aTcQ8AQroPcw==,type:str]
  CLUSTER_API_IP: ENC[AES256_GCM,data:VQ6oYLOLAVgtpxj74dc=,iv:KvgSqDctrjG8AgUJpOOutUb6+xx3LPGBwr+5f2511nI=,tag:FaBYQFZpvVw5f3l5DFKIZQ==,type:str]
  CLUSTER_DNS_IP: ENC[AES256_GCM,data:lvdJFzF7nWIkCVpxaA==,iv:D0GmNiXmlEBSWUsHfO+enQNnZt7rLvXyHYGZsG2QXI8=,tag:QEHjOzlnZpQqtG9sClJ6sA==,type:str]
  CLUSTER_GATEWAY_EXTERNAL_IP: ENC[AES256_GCM,data:1KuUmBOX1QlMPiKzHR0=,iv:drN0xZCWZ9F9/eo04E/EWCgV3QNdhgAuZciYw08XEBA=,tag:ZlM/Wr6KUrTGHehmWVPSQQ==,type:str]
  CLUSTER_GATEWAY_INTERNAL_IP: ENC[AES256_GCM,data:F4/dL9t6pQTq4Fo+WUw=,iv:R3WislmKWo5poltL5LY9NJrOyywNtSPs7QG8A8SH45Q=,tag:xLAm9nWsvDYK7wSgHSKIAg==,type:str]
  LB_POOL2_START: ENC[AES256_GCM,data:b9B6xqNPrGykflYH4Do=,iv:x6TpeAVW+92t2X0e0HeLXbxVTLXQu8Zd5dczfyLsDb4=,tag:O3cDCy2E6g1Yhk9I9n3hoQ==,type:str]
  LB_POOL2_STOP: ENC[AES256_GCM,data:Cx7MSrJKzyrhgUGt0b4=,iv:FMoKteqYyk93+z3q7O40MYvXw1gTScfUxpS5+WrwMfs=,tag:qilQtip6IyQbc8IdbtuW3w==,type:str]
  LB_POOL_START: ENC[AES256_GCM,data:0D5kepoC2CxlOClqxQ==,iv:aJKkGJvbzQtwcdIqN0fe0ZDAWYNcGCzyGnBCbFMQujs=,tag:7A4TafUcc/MecIpNapUQ1w==,type:str]
  LB_POOL_STOP: ENC[AES256_GCM,data:D8JRN31ceuz/jPa5iCA=,iv:ikA6jW5rrezCBQ9Vu4a+1I6J3Nn32uWhRasRfAgwJoQ=,tag:RSV/8mlyDp70MJC/6EN14w==,type:str]
  NAS_IP: ENC[AES256_GCM,data:7Ya1DCtOwY7h8Xkv1Q==,iv:ZINhJfanFpQj2mTGmZeyZ19FPgcARa6yjvtq8HBo+Wk=,tag:3qUxVBsG/hsLJ1G4z/Onfg==,type:str]
  NODE_IP_1: ENC[AES256_GCM,data:xi58lDTkJPObGmtPQQ==,iv:vEZ5iy5WVxh6FJOydxisG+NcExwrTKy2B768Opo1IsM=,tag:nxMpZhmdYM75v1MiR466kQ==,type:str]
  NODE_IP_2: ENC[AES256_GCM,data:Ql9bEFtMPt5KPXKzwQ==,iv:d0Fw7ir5cqzeuvAxION1+VakkLC11uSCEw2ukNB4BN0=,tag:pqaEsIG5oXH1GQU2Ip6O/g==,type:str]
  NODE_IP_3: ENC[AES256_GCM,data:nAQrVklTtdvG8l3mYg==,iv:QjDDQNN2fiDdDPhUCM90H4tsGPuEsfLT1L4ugRilL5Q=,tag:mqDEtt/lBtb0gJqkGNJbCQ==,type:str]
  SECRET_DOMAIN: ENC[AES256_GCM,data:T3jyt6OL/GKaMGN/,iv:q+szJEnBzg6hBog/KKZ3h5a2bMZP40DgxZobOOvPf+s=,tag:NHWbbRfkCiSU+6MCRMB5/A==,type:str]
  SECRET_DOMAIN_SLUG: ENC[AES256_GCM,data:vrAuayHJJ7pYqExt,iv:3rWa00pDIxt0nsjYmHMjSSN5WCXwc6TbLn4peC2yUFs=,tag:NzPcyQQgJ8GEzWOyGcYk2Q==,type:str]
  CNPG_S3_ENDPOINT: ENC[AES256_GCM,data:kzKEZf/IPLLwvY36Lg1vF7nQJuoj5kLxxlk/jcKKUtMEtGuNxrqL45D/z0QriHoE+ui4B1Jr8NzPfnzFxfYyNkM=,iv:0lNk0qNbOhvtbcPKLmuczl1TH8wUyvXe+fEBAaihEBM=,tag:jBsCyTnBkzGUz6gy7vxwzA==,type:str]
sops:
  age:
    - recipient: age1ctpw7mxxzshknqmtwfn9c202hx0j57tv29fdsx4hym6hm5ed2stqtft3he
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvRk1zNm45cnY4WjdTZ0Zk
        WGNrb2dIMkNYMjNtNUhYdDhsUE5zd0VRYlFzCnZqZGt2eGloczR4TFdVL1czTWN6
        cUM0UUpSUGd0REViVUFLUmtjQWk2ZU0KLS0tIE9uemRXaXMyQzZ2M0lqYTRaYVVW
        a3VtMmRzSEtZcHFaT3NHZXlUaXlMd3MK25BTJAq/h02vwb5EsQAgxKypeHdoXFQd
        GG7rouwf7zlyY59zz6zp2AOpY2izVpg1tP1u5Bp2SHmt6ZApWy5Qhg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-15T02:58:04Z"
  mac: ENC[AES256_GCM,data:ap/A1uQfOOJdTqde5gGSxPW6Fom2lJMWbfnufrPGWVaFcnRO/6424dSGhVggmmHa88Inb2D1ohJxJzoVWe4DxPA3X+OshuOww4aJ0xm5ngcNxbs7NdHDUYHlFxWbeRcW3JU7METc+JLuE0ggqDC24DOsXAWMTE4lbrff2Z/hdS8=,iv:xVw9YN/wzVKapiGng5y0cXrYj2YluF0ealFXUHoLrEI=,tag:zZR12Oxe0QTEbtF4r4cReg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
