apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:xoQULcibxZo4CCA+WMm+XTw2TdqyGEKPB+gkay00A/M=,iv:cimg+8MNFJGtbVDP4BioyVNJq1SM9rrJjm78FGxZWSU=,tag:L/a0D/IisuYYc676s0AIrQ==,type:str]
sops:
  age:
    - recipient: age1hrnksegh2ng9csun3twlvj936x95x4a4ca09p23xvwmzdyz7w5sq7nmr4l
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNENhOG5GSnlxQnc0RzFC
        Yk5HZ2dGTDkyUVBuVFp1aTZIcFhuRXNWdWo4CnBpVU4xbllwalZ4UURIM3p2T1p0
        WDVGUzFYQmt4c2tGdkZGdWZrOHhlMDAKLS0tIFlxalpnakIzQ0pvRTlFd1drWVR4
        eEcwcjRJR3l4cmJsRWtUbWR2U291V0UKa0lWNPFptFXfCKfEIJfdsHiReer3nFF6
        veUhHjuoq411Wz7BTQQECTjujNEoGMGDcy7OK/5jbSVslR62cJn+2Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-26T12:26:40Z"
  mac: ENC[AES256_GCM,data:4O9O14OJymUu7spZ/h3fh6NwGkvyuGp83fHlZHWLKSzASQUS3GNDjx2q/hHjMxEOiq3HpLAy7DyJlVWXDc4IAWLOQO7WHTixwClul+fV9HHzT0qGUaeOmqHCxvx4fNVcEmcyzy50Yqp7hjHY2+8DrpheN1Es27gxZwMqftFnt/M=,iv:UHVXJZJQ0QozriueTdIOcsRJa2WyAhkOtlZ/gK+mu+M=,tag:kg9/JdKSkDHu4kRl83On/g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
