apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:JpK6Dl8PT+Ts1roFR6DBdaGPUgQ1AN7937hQCza+Wws=,iv:fF4Ly5V+DNweHx6f5/qzrmqG+cpzR67elAj74gsX2TM=,tag:g/j88DCtyFoolF2349QfXA==,type:str]
sops:
  age:
    - recipient: age1ctpw7mxxzshknqmtwfn9c202hx0j57tv29fdsx4hym6hm5ed2stqtft3he
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEOTladytjVTNCQ0swbGN0
        VTFzR2NNL1hIZndqN1FWdUt1RlZndmhPUG5nCjVGV2laRmNSeEFoTWpMSnZVN2hk
        RGluM1Y0dGd2YnR6VkZKbStvajZlVncKLS0tIE5EVHJ1SS9FQW8wb1QxS1Y5NUFW
        THB1U1l5TmxHSGRWWFVsYUszTEtiZkEK+43bznMI94Oah/7Kj7EuJWw99HH70xp+
        M3ZJ6qkk8Pi3XX2tY42wq6Cv/0tdlihTL/VxhMBme+QZGTGTzv4yWg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-02T14:15:50Z"
  mac: ENC[AES256_GCM,data:f05uAQTSdvm1TUHQrz7H99WV3gXhcOgEGUN/wxDLv+8IQFi0ro9/bGULBlsDU0rBB8aJILLXo1hzcmWufn2j9jWp8t816KKPGOOIQMcTLf5Xhj3rZnFWG67DSdEfxv052/LP9Fja+h0YBZYob2NBOdwNySTFrBZ889DIa5OzfQM=,iv:lPeAvgeEocCrOi+adbKKVmUKxj2tXsxsyVu8KKLqC/I=,tag:jVjrzu1bIDWJh4ntJPVRsg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
