apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:MP5if5thAfSDF/7qVCgatm0F+FYAHNRjG7YC1vYZEBw=,iv:P29ByH5MHeJRw9Ke2dfXwv7HkpsXSGaa+WL1Txog8qA=,tag:4pNd4VfnPnGRQhRZmtbJ+A==,type:str]
sops:
  age:
    - recipient: age1ctpw7mxxzshknqmtwfn9c202hx0j57tv29fdsx4hym6hm5ed2stqtft3he
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTmdQUk1UM2JNZWhjOXZJ
        RU82QlgwRXQ0RGpVUVFqUlNNSmxHZTAyZUZ3ClFCYVVsOTZlY2l6VytEQlMySFM3
        Y2plSkM5T2pTRTZQbDhqREVtaUYvQm8KLS0tIFY3TWtWS0Vrc2pOeW1JaTNCZ0gr
        bGZFUGVJdXVSTGVVRFBrOGlvUm1QT2sK3+O9Lzh58vjde2b6aQeBBGLp8RThWNGK
        WqMRp+0UYJdHLRKdvLGQLB8AhpQ/XnpdiJaMNXlFkaGUL1NUxT/4bQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-05T00:08:25Z"
  mac: ENC[AES256_GCM,data:fm8qfUW9ApHfK7utS+TE0dYy9UyFe4xTRZvwDtU+ENicttG0NrShDdxTEdu1lb7vhDvPDI4GwZz9WRK0bSFg4zjHh9JFGyFLOKjiNX4BnVfZ7ubhRvl1kv5hWYRMxfFvUTDfI8BYBxCeeFAJRnuiO8s2t9q8wny0RyUaePoT34c=,iv:YwJswgXNSt8f+JWfWjzijpO9HqH/R0qmsnPqIwvzTiU=,tag:pjZb6TEFqF9uxAmCmGMqEQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
