---
# yaml-language-server: $schema=https://kubernetes-schemas-ebx.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: romm-postgres
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  storage:
    storageClass: ceph-block
    size: 5Gi
  bootstrap:
    initdb:
      database: romm
      owner: romm
  backup:
    volumeSnapshot:
      className: csi-ceph-blockpool
  monitoring:
    enablePodMonitor: true
