---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: romm
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: romm-secret
    creationPolicy: Owner
    template:
      data:
        ROMM_AUTH_USERNAME: "{{ .ROMM_AUTH_USERNAME }}"
        ROMM_AUTH_PASSWORD: "{{ .ROMM_AUTH_PASSWORD }}"
        ROMM_AUTH_SECRET_KEY: "{{ .ROMM_AUTH_SECRET_KEY }}"
        IGDB_CLIENT_ID: "{{ .IGDB_CLIENT_ID }}"
        IGDB_CLIENT_SECRET: "{{ .IGDB_CLIENT_SECRET }}"
        STEAMGRIDDB_API_KEY: "{{ .STEAMGRIDDB_API_KEY }}"
  dataFrom:
    - extract:
        key: romm
