---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: romm-library-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NAS_IP}
    path: /mnt/HDD1X4/apps/romm/library
  claimRef:
    name: romm-library
    namespace: games
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-library
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  volumeName: romm-library-pv
  storageClassName: ""
