---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: emby
spec:
  chartRef:
    kind: OCIRepository
    name: emby
  interval: 1h
  values:
    controllers:
      emby:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/emby
              tag: 4.9.3.0@sha256:7c33d88d0186ad7abcc6e53566e9db8766687daa5510cddc13094e25bc5a5dfb
            env:
              TZ: Europe/Paris
              EMBY_ADVERTISE_URL: https://emby.kryzql.space:443,http://192.168.42.110:8096,http://emby.media.svc.cluster.local:8096
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /identity
                    port: &port 8096
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              claims:
                - name: gpu
              requests:
                cpu: 100m
              limits:
                memory: 8Gi
    defaultPodOptions:
      resourceClaims:
        - name: ${APP}-gpu
          resourceClaimTemplateName: emby
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 192.168.42.110
        externalTrafficPolicy: Local
        ports:
          http:
            port: *port
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |-
            conditions: ["[STATUS] == 401"]
        hostnames:
          - "{{ .Release.Name }}.kryzql.space"
        parentRefs:
          - name: envoy-external
            namespace: network
        rules:
          - # Ref:
            backendRefs:
              - identifier: app
                port: *port
            filters:
              - type: RequestHeaderModifier
                requestHeaderModifier:
                  remove:
                    - Range
            matches:
              - path:
                  type: PathPrefix
                  value: /library/streams
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      media:
        type: nfs
        server: NAS.internal
        path: /mnt/HDD1X4/media
        globalMounts:
          - path: /media
            readOnly: true
      tmp:
        type: emptyDir