---
# yaml-language-server: $schema=https://kubernetes-schemas-ebx.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falco
spec:
  chartRef:
    kind: OCIRepository
    name: falco
  interval: 1h
  values:
    driver:
      kind: modern_ebpf
    falco:
      json_output: true
      json_include_output_property: true
      metrics:
        enabled: true
        interval: 15m
        output_rule: true
    webserver:
      prometheus_metrics_enabled: true
    serviceMonitor:
      create: true
      interval: 15s
    falcosidekick:
      enabled: true
      config:
        loki:
          hostport: "http://victoria-logs-server.observability.svc.cluster.local:9428"
          endpoint: "/insert/loki/api/v1/push"
          minimumpriority: "debug"
          format: "json"
        alertmanager:
          hostport: "http://kube-prometheus-stack-alertmanager.observability.svc.cluster.local:9093"
          endpoint: "/api/v2/alerts"
          minimumpriority: "warning"
      serviceMonitor:
        enabled: true
    customRules:
      cni-exceptions.yaml: |-
        - rule: Drop and execute new binary in container
          append: true
          exceptions:
            - name: cni_binaries
              fields: [proc.exe]
              comps: [startswith]
              values:
                - ["/opt/cni/bin/"]
    falcoctl:
      artifact:
        install:
          refs:
            - "falco-rules:5"
            - "falco-incubating-rules:5"
        follow:
          refs:
            - "falco-rules:5"
            - "falco-incubating-rules:5"
