---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgres
spec:
  instances: 3
  # renovate: datasource=docker depName=ghcr.io/cloudnative-pg/postgresql
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  storage:
    storageClass: ceph-block
    size: 5Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi
  bootstrap:
    initdb:
      database: immich
      owner: immich
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS cube;
        - CREATE EXTENSION IF NOT EXISTS earthdistance;
        - CREATE EXTENSION IF NOT EXISTS vector;
  backup:
    retentionPolicy: "7d"
    barmanObjectStore:
      destinationPath: s3://cnpg-backups/immich-postgres
      endpointURL: ${CNPG_S3_ENDPOINT}
      s3Credentials:
        accessKeyId:
          name: immich-postgres-backup-secret
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: immich-postgres-backup-secret
          key: AWS_SECRET_ACCESS_KEY
      wal:
        compression: bzip2
      data:
        compression: bzip2
  monitoring:
    enablePodMonitor: true
