---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgres
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  storage:
    storageClass: ceph-block
    size: 5Gi
  bootstrap:
    initdb:
      database: immich
      owner: immich
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS vector;
  monitoring:
    enablePodMonitor: true
