---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-postgres-backup
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: immich-postgres-backup-secret
    template:
      data:
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
        ENDPOINT_URL: "https://{{ .CLOUDFLARE_ACCOUNT_TAG }}.r2.cloudflarestorage.com"
  dataFrom:
    - extract:
        key: cnpg-backup
    - extract:
        key: cloudflare
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/scheduledbackup_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: immich-postgres
spec:
  schedule: "0 3 * * 0"
  backupOwnerReference: self
  cluster:
    name: immich-postgres
  method: barmanObjectStore
