---
apiVersion: v1
kind: LimitRange
metadata:
  name: limits
spec:
  limits:
    - type: Container
      default:
        memory: 256Mi
      defaultRequest:
        cpu: 10m
        memory: 64Mi
      max:
        memory: 8Gi
