---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: homepage
  values:
    controllers:
      homepage:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/gethomepage/homepage
              tag: v0.10.9
            envFrom:
              - secretRef:
                  name: homepage-secret
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: false

    service:
      app:
        controller: homepage
        ports:
          http:
            port: 3000

    persistence:
      config:
        type: configMap
        name: homepage-config
        globalMounts:
          - path: /app/config/settings.yaml
            subPath: settings.yaml
          - path: /app/config/widgets.yaml
            subPath: widgets.yaml
          - path: /app/config/bookmarks.yaml
            subPath: bookmarks.yaml
          - path: /app/config/services.yaml
            subPath: services.yaml

    route:
      app:
        hostnames:
          - homepage.kryzql.space
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: http
