apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:S2JvfAzb7ZO0Bj8G+vSqriXdRtn5OC6by7OOgl3UzIxzv5YVVvyVKYzUKJiTf4LmL/Uah8IqBH/1w8CdxjJ9w6wmfOXtDG+00iKSJdUzgJ4CgTIb9sGdc8xI+QUFGObEgg1vx/2TcwGxgiP7VKVPmFe0TwEAeqa64PEnMm9YsCM2b1L1oJWRYVkxRNzRX+jPbvLzL/l6MrKnREAKXwMmBo26wwnRcxtUuGKNuC0mQwBUuqzd,iv:tF/WhbepxQz7nsLCvBSPymXL+YKEiJaqqjw71gzZZIw=,tag:OgibxZ9qBdq/KBpiqoUu2A==,type:str]
sops:
  age:
    - recipient: age1ctpw7mxxzshknqmtwfn9c202hx0j57tv29fdsx4hym6hm5ed2stqtft3he
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2N1YrV3pVZ2hxUzVjdEt0
        ZDR3N3BnL3RlSlhnWExlcnJtYjFRakppRFhnCmlSaCtIb3hvamtncE1nMUdqT2VH
        OE00MWtxclJOLy9BQ3JRa3BMSDREZ2sKLS0tIEtnM2FYNlZkQmpSdDdVd3ltTFZW
        bG9KankreU9lbSt3bmVNU2szOFhKdFkKdRQyTHItwaQoBfMi7PIoD3zbHCJSXfzG
        yF1liHwLyogdwxPdZ3iqffVm4Ld+JCufovgCBoMNA1Myb4sB7g8dow==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-05T00:08:25Z"
  mac: ENC[AES256_GCM,data:UIHpbWiWMQMmgaYNtRZwodLLTXajo72GCAnOC7g3uaJa9FOglqQN4CBe5ELR7tt1lWAYvtSkYCt1o+p40MRcfiLlU1k3aUISvflQad8SMzIiI+thXCbFD5xF22qSGyzbqCvTZa5DypQdDcV4x228uDDbGt3nHCSHqDBnD+XJ9xc=,iv:BWKJteaMaLt4/1kkT19txKiycDXOdFK1NzIf1CvWZKk=,tag:ODmYkVWGa1ggHO51kRPySQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
