apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:8b/nmrZFIUEq3/IjelhJ3/U3VpHGOaZrt94x6sGJgl1wRvmi3pARXd39iHoW1bs0nmD5K8zYgWgxbm6GF9CEDtCKfwMB3djb2aV+eG36gfYtPbFqX8LEsaR/kbpI8e8VC1oVm3ZmQSf8GsdnA+lb3vNNhyzj6VkQfPeZbQHICrerRmfQs8dlAD82f2F6p0oA97vvVkZzoWXZ3NqADSTRT4Ouk6VUe6gLY5AbAtRMDwfyLAGD,iv:iaWmMV3wXSwwc5t1hRKyKIvlWrOYZVScnONwynzWM4U=,tag:N6dcs5k3Q1QCABdnqeGUdQ==,type:str]
sops:
  age:
    - recipient: age1ctpw7mxxzshknqmtwfn9c202hx0j57tv29fdsx4hym6hm5ed2stqtft3he
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0V0lmc0NJbUdnV09IUzg2
        MzZHQnZ4SFkzckNUWWI2L05IT09PMFNmNGdvCmgra1N5bndkYnBvMG9TbjUxU205
        VGp6QWFKODhMdStvRkgrai9uZW9JSlUKLS0tIHFRZW9naDJwWGVpeFB3SnR1R2I0
        dGJBNmNIMkRRdDh4dVM0ZHU0bzM0VkkK35DcUlH7nW7/LuAHnxHdQ/yD8CTb+lVs
        0v7X+WcaJ3VIWskYHqM0oTQadYC2+GmwttZSUmmuoBTEjgQsOPiPZQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-02T14:15:50Z"
  mac: ENC[AES256_GCM,data:JLNQ+CuQC1NavOWOhbBO9BgVB2orewtWymex8Rwnf/d+giaamEw17ETl7lnFdDKAP8H6oLE58cPUTQLmopwC5PxgdPCyVr1fhmkvBE6bWybp8OcHeS6449udABQDOvvd+2y9gJ8MVM/VyKhmYi0LGcu3XyfXjJaCWgDtUGp6iWA=,iv:IVvukNXcr8eolrEH6aKKs0mYUWVSzkmqvpuV1/X64sk=,tag:gAm+kphhwz82xdulN6b/bQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
