apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:6KStDW6uGskXV+A+8xIMWsVIc993n5Q6Og7lVcfMlWr0uDeaG0jNRCQyFfV9aYADOciubwLkfJqLAkEuh/8dq4bnyU6GVuEN7NlogO9neTSnxTXi1IxHYqsu4M++16GLsvmUkMuQNUeTIA4OEyJ9xZ2D5A63z/3H9GrYExmcaovmXOal0NzgDS1BGNC0lcrbz5OZrrjTI3X1OmeeXI92OvBQtIL/NB150bEr3uEYZ83O5fOX,iv:rC5uMMTOXGOSYvOd/y1G9MO1CH+j6tmxbupW1Qfg6Ao=,tag:Bz6kbvvSsc2DUZRiRreRVw==,type:str]
sops:
  age:
    - recipient: age1ctpw7mxxzshknqmtwfn9c202hx0j57tv29fdsx4hym6hm5ed2stqtft3he
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSGZ5cWFjTzdZeG1sbUtG
        Z09YeUdWMW5sZHJXMVF4b2d6dk5UMko3VlJrClN2M3U3TDEzNytsdUFPcnNkMlpp
        WSs2Nk0yQU5mV3krU1BaRis4dldreXMKLS0tICs2dFNWanQrdW9KVlhKc01rOCt3
        TkpTRURoL1czWjA2T294b3V0ZStkcUEKakDjQuV7rgoS2b67QTjM0D+ujoPQwIDb
        pdhxu8NIkCWKG8XwsaQci0W61ecuMtiIGl5sUqQNeJSdsByFn0tq+Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-31T16:43:32Z"
  mac: ENC[AES256_GCM,data:PwQw+In+C+iQ6Ev/ZvJXKoVMacIxGzI63RN328pwPPRJ2pXtANh0EQF4FE1+pIJThlVdn2eiRihgbeaDZkoWAlLJ/SOseZUBGL2SYDq4iGzL/i+J7eaRFLgdGBN3oJOkq+mFquoJ1kpDgWaMlvvWpzM74Kpb+F/qiQP+84jbDXI=,iv:/x7RctCF/+/nX3glHvAiKrPLCgMNeR5IgK3AxtBxOmA=,tag:kFS2nD6Yus/3H9cltNDTkw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
