---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: lan-icmp
spec:
  module: icmp
  prober:
    url: blackbox-exporter-lan.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - jetkvm-1.internal
        - jetkvm-2.internal
        - jetkvm-3.internal
        - ${NAS_IP}
        - node01.internal
        - node02.internal
        - node03.internal
  metricRelabelings:
    - targetLabel: service
      replacement: blackbox-exporter-lan
      action: replace
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: lan-tcp
spec:
  module: tcp_connect
  prober:
    url: blackbox-exporter-lan.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - ${NAS_IP}:2049
  metricRelabelings:
    - targetLabel: service
      replacement: blackbox-exporter-lan
      action: replace