---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  chartRef:
    kind: OCIRepository
    name: cert-manager
  interval: 1h
  values:
    crds:
      enabled: true
    dns01RecursiveNameservers:
      - https://cloudflare-dns.com:443/dns-query
    dns01RecursiveNameserversOnly: true
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
    webhook:
      replicaCount: 2
      podDisruptionBudget:
        enabled: true