apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Xqqg1F7idOs9jFAy98bz4fH1lwACoHYOy/rOY6PfWq3L8SDFuB1S6w==,iv:YOtT80tthbOe8nygYbCS8Qg/3vgBPUPHNYofvuDn744=,tag:uuAk99oS90i7TQsuCVCk7g==,type:str]
sops:
  age:
    - recipient: age1ctpw7mxxzshknqmtwfn9c202hx0j57tv29fdsx4hym6hm5ed2stqtft3he
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtMnBLRnZKbnYyWEJ4dThy
        RzV4cXpqVVJYQkFlWXdHT0wwNzR5cWJzK0VvCkYvUXZlOElEVCsrY3Zoc1NGRG9t
        SHJxVHVrNHd1UmRRbVBCNUo2SHFjMGcKLS0tIEFwazRIVU4xT2FkNUhseFJRNmlS
        ZkNLK2Y5SStqbXBOUTVZbUpEejlTZDgKfFJvaY5TZgs4SBwum07AVnvf8mmHoiGk
        BaPKN9SRsMwmCicLjzk4U/qTbAc6vUOSsXl8EH5mq89eJLrebB/8qQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-31T16:22:28Z"
  mac: ENC[AES256_GCM,data:fF+rLIq1XfF8yGfS1F1Lo8YQbkGyKe/yOBjMfA4m0jvkHhlaTnS1dzkVlu2LhhKMgpxdqVpAeHD+zorXUebrpqd6S1RRYhHwBgIIyqHgvVru2zDpggkYlwsRjcVesh8JYKS1Xb0DywOC57p7tTE/5P/BcKY7m2nw8vuCPB/jfd4=,iv:F1fIu8WSiy98ffsH2lL4mJjw2tPoe/+ILhKPJFGvcjA=,tag:OUxwqBVv87cNlRxTPRMR9w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
