apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:IhOgz9tZXGAFSoo+wgpbzqd/kky/wtYF5M3RsJV8gTI6M/uGzcQP2w==,iv:Bj0AdCgXwGXIeSQOyo16Xv6mHrWYRR77ZEs8su2wWBU=,tag:WKa4KBl6X5ZdntHDHVEy7Q==,type:str]
sops:
  age:
    - recipient: age1hrnksegh2ng9csun3twlvj936x95x4a4ca09p23xvwmzdyz7w5sq7nmr4l
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVnMvWTBKc1loUmViOWtR
        SlJ0RHBUbGp4QWViTFlzT2FtK3NDRHd0T0dJCkJBNWUvc2JnZEdabDNiS2Q4QjEy
        dE5SMXdDOVY2NnZldkZlYXI4U3YvUlkKLS0tIHh5TUhDdjh4L1d5UFptQVlCV2pm
        U3dObnJWZG5HRXJPTXFQOXhwNFIwVFkK/xq+ileRxHIRWWt4IsGHwpb0KhjiU082
        3ivOn7IPsS0Xv0WSVpLO6wQCjyMS7S1pOh4XA9SnMRHqgN64yvQa5A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-26T12:26:40Z"
  mac: ENC[AES256_GCM,data:+LCkI38GikUdLIwgpV+CoIkEMc16z+lwV3iAjZwPsjq2BtlRAIoypslvHdZfm6ThJngkGXLfJRgvuBspOlOKI/Nnj9hd7eVRuvv9Nt7LoeK64CXU3bkzEiTNCxHXi2/w+CHA6QFWbjRcoycXoif/xQJ5nL21LIsyEj277fXqR8Q=,iv:XvzsApCZahcDe5+qRF3tCc8cdiuY8e+pnC79eHbMNDs=,tag:37uZjl+gbX60k0dOrLYWvw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
