apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:u7bKfm0EIaggZ2azs8iK96KVSUpOYB9HZ9VT4fCxs8VLfb3iKZFFlg==,iv:7V3gpyzQPf8JXj4OsqMPyomeKT8cLvx34R2kiaLFx/w=,tag:VMQvI+SiOG5I6Mnq4UumWQ==,type:str]
sops:
  age:
    - recipient: age1ctpw7mxxzshknqmtwfn9c202hx0j57tv29fdsx4hym6hm5ed2stqtft3he
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2MlRHVk0ra0w5ODhKRndj
        M0J4WmxxZVdvSlJXRllPMGpsdU4yejBMa0dzClFZNjVtZWY2SklLeG9WUys1Qmho
        RGEzL2k4VStjWWc5RXBnOWpXVmNyc2MKLS0tIFE1cmwrNlo1K05VZU4rbTU3MGZj
        eWNRWER5VWlHNEhCb01UcnRGVEZUdW8KHJ1rt1gIgxBrtyPuPKiR1s0AQxPQA8tk
        QRMTHpwgSx67br1TWYZDHDJjSWKQMmb+lBCYN/hILEgfdjX82a38Mg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-02T14:15:50Z"
  mac: ENC[AES256_GCM,data:xqY/n9EtSwZLcJWSUTfkqwSz+rW0tFEuPwdNH0OuoQgyeTzpaxfW/SVXA6ayoA61iUTuff5aL/pEA5HhZaS4q6LP1pDCA5jDRft5uP+bu169H4u+MyuWek/liHSTrv358g+275B9OXbgpA9oLAcHrzcG5bMtYdpKoqXU87qyYbY=,iv:kQI7jgQtSLjN18Vm/rZ0illAQDCUK6VhXdHNvo8KDjc=,tag:56rIK4IeW4GLEAXMI543jw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
