---
machine:
  type: controlplane
  nodeLabels:
    topology.kubernetes.io/zone: mesh
---
apiVersion: v1alpha1
kind: HostnameConfig
hostname: node03
---
apiVersion: v1alpha1
kind: LinkAliasConfig
name: node03-to-node01
selector:
  match: link.driver == "thunderbolt-net" && link.bus_path == "1-1.0"
---
apiVersion: v1alpha1
kind: LinkConfig
name: node03-to-node01
addresses:
  - address: 169.254.255.23/32 # node03
mtu: 65520
routes:
  - destination: 169.254.255.21/32 # node01
    metric: 2048
up: true
---
apiVersion: v1alpha1
kind: LinkAliasConfig
name: node03-to-node02
selector:
  match: link.driver == "thunderbolt-net" && link.bus_path == "0-1.0"
---
apiVersion: v1alpha1
kind: LinkConfig
name: node03-to-node02
addresses:
  - address: 169.254.255.23/32 # node03
mtu: 65520
routes:
  - destination: 169.254.255.22/32 # node02
    metric: 2048
up: true