---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nut-shutdown
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: nut-shutdown-secret
    creationPolicy: Owner
  data:
    - secretKey: talosconfig
      remoteRef:
        key: talos
        property: config
