---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: operator-oauth
    template:
      data:
        client_id: "{{ .TS_OAUTH_CLIENT_ID }}"
        client_secret: "{{ .TS_OAUTH_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: tailscale
