---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale
spec:
  chartRef:
    kind: OCIRepository
    name: tailscale
  interval: 1h
  values:
    controllers:
      tailscale:
        annotations:
          reloader.stakater.com/auto: "true"
        serviceAccount:
          name: tailscale
        containers:
          app:
            image:
              repository: ghcr.io/tailscale/tailscale
              tag: v1.94.2
            env:
              TS_KUBE_SECRET: tailscale-state
              TS_USERSPACE: "true"
              TS_AUTH_ONCE: "true"
              TS_HOSTNAME: homelab
              TS_EXTRA_ARGS: "--advertise-exit-node"
            envFrom:
              - secretRef:
                  name: tailscale-oauth
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        seccompProfile:
          type: RuntimeDefault
