---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: paperless
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: paperless
      app.kubernetes.io/instance: paperless
      app.kubernetes.io/controller: paperless
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: network
            gateway.networking.k8s.io/gateway-name: envoy-internal
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: selfhosted
            app.kubernetes.io/name: glance
      toPorts:
        - ports:
            - port: "8000"
              protocol: TCP
  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s:k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: paperless
            app.kubernetes.io/instance: paperless
            app.kubernetes.io/controller: redis
      toPorts:
        - ports:
            - port: "6379"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: paperless
            app.kubernetes.io/instance: paperless
            app.kubernetes.io/controller: tika
      toPorts:
        - ports:
            - port: "9998"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: paperless
            app.kubernetes.io/instance: paperless
            app.kubernetes.io/controller: gotenberg
      toPorts:
        - ports:
            - port: "3000"
              protocol: TCP
---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: paperless-redis
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: paperless
      app.kubernetes.io/instance: paperless
      app.kubernetes.io/controller: redis
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: paperless
            app.kubernetes.io/instance: paperless
            app.kubernetes.io/controller: paperless
      toPorts:
        - ports:
            - port: "6379"
              protocol: TCP

---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: paperless-tika
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: paperless
      app.kubernetes.io/instance: paperless
      app.kubernetes.io/controller: tika
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: paperless
            app.kubernetes.io/instance: paperless
            app.kubernetes.io/controller: paperless
      toPorts:
        - ports:
            - port: "9998"
              protocol: TCP

---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: paperless-gotenberg
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: paperless
      app.kubernetes.io/instance: paperless
      app.kubernetes.io/controller: gotenberg
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: paperless
            app.kubernetes.io/instance: paperless
            app.kubernetes.io/controller: paperless
      toPorts:
        - ports:
            - port: "3000"
              protocol: TCP

