---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: paperless
  values:
    controllers:
      paperless:
        replicas: 1
        strategy: Recreate
        pod:
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: ScheduleAnyway
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: paperless

        containers:
          app:
            image:
              repository: ghcr.io/paperless-ngx/paperless-ngx
              tag: 2.20.10

            env:

              PAPERLESS_URL: https://paperless.kryzql.space
              PAPERLESS_TIME_ZONE: Europe/Paris

              PAPERLESS_REDIS: redis://paperless-redis:6379

              PAPERLESS_TIKA_ENABLED: "1"
              PAPERLESS_TIKA_ENDPOINT: http://paperless-tika:9998
              PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://paperless-gotenberg:3000

              PAPERLESS_TASK_WORKERS: "1"
              PAPERLESS_THREADS_PER_WORKER: "2"

              PAPERLESS_CONSUMPTION_DIR: /usr/src/paperless/consume
              PAPERLESS_DATA_DIR: /usr/src/paperless/data
              PAPERLESS_MEDIA_ROOT: /usr/src/paperless/media
              PAPERLESS_EXPORT_DIR: /usr/src/paperless/export

              PAPERLESS_OCR_LANGUAGE: fra
              PAPERLESS_OCR_LANGUAGES: fra

              PAPERLESS_OCR_ROTATE_PAGES: "1"
              PAPERLESS_OCR_DESKEW: "1"
              PAPERLESS_OCR_CLEAN: clean

              PAPERLESS_ADMIN_USER:
                valueFrom:
                  secretKeyRef:
                    name: paperless-secret
                    key: PAPERLESS_ADMIN_USER
              PAPERLESS_ADMIN_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: paperless-secret
                    key: PAPERLESS_ADMIN_PASSWORD
              PAPERLESS_SECRET_KEY:
                valueFrom:
                  secretKeyRef:
                    name: paperless-secret
                    key: PAPERLESS_SECRET_KEY
            resources:
              requests:
                cpu: 200m
                memory: 1Gi
              limits:
                memory: 3Gi




      redis:
        containers:
          redis:
            image:
              repository: ghcr.io/valkey-io/valkey
              tag: 9.0.3
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                memory: 256Mi
      tika:
        containers:
          tika:
            image:
              repository: apache/tika
              tag: 2.9.2.1
            resources:
              requests:
                cpu: 200m
                memory: 512Mi
              limits:
                memory: 1Gi

      gotenberg:
        containers:
          gotenberg:
            image:
              repository: gotenberg/gotenberg
              tag: 7
            args:
              - gotenberg
              - --chromium-disable-routes=true
            resources:
              requests:
                cpu: 200m
                memory: 512Mi
              limits:
                memory: 1Gi

    service:
      paperless:
        controller: paperless
        primary: true
        ports:
          http:
            port: 8000
      redis:
        controller: redis
        ports:
          redis:
            port: 6379
      tika:
        controller: tika
        ports:
          http:
            port: 9998
      gotenberg:
        controller: gotenberg
        ports:
          http:
            port: 3000

    persistence:
      data:
        existingClaim: paperless
        advancedMounts:
          paperless:
            app:
              - path: /usr/src/paperless/data
              - path: /usr/src/paperless/media

      consume:
        type: nfs
        server: NAS.internal
        path: /mnt/HDD1X4/apps/paperless/incoming
        advancedMounts:
          paperless:
            app:
              - path: /usr/src/paperless/consume

    route:
      app:
        hostnames:
          - paperless.kryzql.space
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: paperless
                port: http