---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tandoor
spec:
  chartRef:
    kind: OCIRepository
    name: tandoor
  interval: 1h
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      tandoor:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: vabene2000/tandoor-recipes
              tag: "1.5.17"
            envFrom:
              - secretRef:
                  name: tandoor-secret
            env:
              TZ: Europe/Paris
              DB_ENGINE: django.db.backends.postgresql
              POSTGRES_HOST: localhost
              POSTGRES_PORT: "5432"
              POSTGRES_USER: tandoor
              POSTGRES_DB: tandoor
              ALLOWED_HOSTS: "*"
              CSRF_TRUSTED_ORIGINS: "https://tandoor.${SECRET_DOMAIN}"
              GUNICORN_CMD_ARGS: "--timeout 60 --workers 2"
            resources:
              requests:
                memory: 256Mi
                cpu: 50m
              limits:
                memory: 512Mi
          postgres:
            image:
              repository: postgres
              tag: "16"
            env:
              POSTGRES_USER: tandoor
              POSTGRES_DB: tandoor
              POSTGRES_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: tandoor-secret
                    key: POSTGRES_PASSWORD
              PGDATA: /var/lib/postgresql/data/pgdata
            resources:
              requests:
                memory: 128Mi
                cpu: 20m
              limits:
                memory: 256Mi

    service:
      app:
        controller: tandoor
        ports:
          http:
            port: 8080

    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |-
            ui:
              hide-hostname: true
        hostnames:
          - tandoor.${SECRET_DOMAIN}
        parentRefs:
          - name: envoy-internal
            namespace: network

    persistence:
      media:
        type: nfs
        server: ${NAS_IP}
        path: /mnt/HDD1X4/cuisine
        advancedMounts:
          tandoor:
            app:
              - path: /opt/recipes/mediafiles
      postgres-data:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 2Gi
        storageClass: ceph-block
        advancedMounts:
          tandoor:
            postgres:
              - path: /var/lib/postgresql/data

    disableDefaultSecurityContext: All
