---
# yaml-language-server: $schema=https://kubernetes-schemas-ebx.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-postgres-backup
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: nextcloud-postgres-backup-secret
  dataFrom:
    - extract:
        key: cnpg-backup
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: nextcloud-postgres-store
spec:
  retentionPolicy: 7d
  configuration:
    destinationPath: s3://cnpg-backups/nextcloud-postgres
    endpointURL: ${CNPG_S3_ENDPOINT}
    s3Credentials:
      accessKeyId:
        name: nextcloud-postgres-backup-secret
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: nextcloud-postgres-backup-secret
        key: AWS_SECRET_ACCESS_KEY
    wal:
      compression: bzip2
    data:
      compression: bzip2
---
# yaml-language-server: $schema=https://kubernetes-schemas-ebx.pages.dev/postgresql.cnpg.io/scheduledbackup_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: nextcloud-postgres
spec:
  schedule: "0 0 3 * * 0"
  backupOwnerReference: self
  cluster:
    name: nextcloud-postgres
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
