---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dynacat
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: dynacat-secret
    creationPolicy: Owner
  data:
    - secretKey: RADARR_API_KEY
      remoteRef:
        key: radarr
        property: api_key
    - secretKey: SONARR_API_KEY
      remoteRef:
        key: sonarr
        property: api_key
    - secretKey: TMDB_API_KEY
      remoteRef:
        key: tmdb
        property: api_key
    - secretKey: EMBY_API_KEY
      remoteRef:
        key: emby
        property: glance_api_key
    - secretKey: READARR_API_KEY
      remoteRef:
        key: readarr
        property: api_key
    - secretKey: ABS_TOKEN
      remoteRef:
        key: audiobookshelf
        property: token
    - secretKey: LIDARR_API_KEY
      remoteRef:
        key: lidarr
        property: api_key
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: flux
        property: FLUX_GITHUB_TOKEN
    - secretKey: NAVIDROME_USER
      remoteRef:
        key: navidrome
        property: username
    - secretKey: NAVIDROME_PASS
      remoteRef:
        key: navidrome
        property: password
