---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: etcd-snapshot
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: etcd-snapshot-secret
    creationPolicy: Owner
  data:
    - secretKey: talosconfig
      remoteRef:
        key: talos
        property: config
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: cnpg-backup
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: cnpg-backup
        property: AWS_SECRET_ACCESS_KEY
