apiVersion: v1
kind: Secret
metadata:
  name: open-webui-secret
stringData:
  WEBUI_SECRET_KEY: ENC[AES256_GCM,data:q2GlbhF6z9nyxhhPpZ2qqp3nZVLmGOhiIGGfinMH7tAwdKKLO/1nHUBzen54ajnIETBJ/ZoXOS9/HEynQ/z+TQ==,iv:dyiqeqOHlWA8DJZJhp4Ubv+jXAqtlO/v5V3l3KTogFw=,tag:nPiQj5hRECcftO03aNdqRQ==,type:str]
sops:
  age:
    - recipient: age1ctpw7mxxzshknqmtwfn9c202hx0j57tv29fdsx4hym6hm5ed2stqtft3he
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBheE1UVUZ2eTZORjI3OEdu
        ZkhTNkxCbjhlcVNmbnJLTW0xVVRHSEtXQXhzCkl1dWRhVlRhVHdwa3RkTzRuc2FO
        RGZRUzhEM3FpbzRWMFExa1lqT2VIUk0KLS0tIFhFaitVb1RPaWdMZFdOdmo4dENx
        QnpSM1M1cWdhOUJHQmREYmNsaytTL0EKOaxQELzhqtHWOFokjeNYEvZ8tWuJP2Xk
        V7nTX5mlptoy9MCZSgTtowYCLFuD1rWu1bbDgjzpLYzr0L0dKXGFmg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-13T00:48:19Z"
  mac: ENC[AES256_GCM,data:BJ7GcP/4SxBHSWkfyEfNGlT+bWvoptm0rzNNispmGGC6hcQkt1097rmE+beGcO23vlEeM21/SFIn+ZcBC3Lq1KFM40bjzwmKWdjUAz3uZtjF75H3Mjw8FFF4vSxRGQW5PNDl+bdla1hmOdPeT03AWFS9T3yALHbNoRt2ZXYQO5s=,iv:XjIX2bmm+Wfvbe8p5shFwRhtPezGWoTWbgaUWpEQXec=,tag:O5PfM/AR7+fUNxlbSpQMlw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
