---
# yaml-language-server: https://k8s-schemas.bjw-s.dev/cilium.io/ciliumloadbalancerippool_v2.json
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: services
spec:
  allowFirstLastIPs: "Yes"
  blocks:
    - start: ${LB_POOL_START}
      stop: ${LB_POOL_STOP}
    - start: ${LB_POOL2_START}
      stop: ${LB_POOL2_STOP}
---
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: gateways
spec:
  blocks:
    - start: ${CLUSTER_GATEWAY_INTERNAL_IP}
      stop: ${CLUSTER_GATEWAY_EXTERNAL_IP}