---
# yaml-language-server: https://k8s-schemas.bjw-s.dev/cilium.io/ciliumloadbalancerippool_v2.json
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: services
spec:
  allowFirstLastIPs: "Yes"
  blocks:
    - start: 192.168.42.50
      stop: 192.168.42.109
    - start: 192.168.42.121
      stop: 192.168.42.199
---
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: gateways
spec:
  blocks:
    - start: 192.168.42.110
      stop: 192.168.42.120