apiVersion: v1
kind: Secret
metadata:
  name: pihole-secret
stringData:
  FTLCONF_webserver_api_password: ENC[AES256_GCM,data:qp8Mx3p3EDC3DJcyMDqeuBN8B6UCmz+ZrpnDKA==,iv:+JDl7j9wJOGmaBUeieD/K9R95XpMux3PBVDw848nOHM=,tag:tXENotBWbBO4CF6To72kIQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRFFqdHBqRUpmUkhxNXk3
        QS8rTm5IampCUkJJU3FFRXluamRPeWFoakZVCnZ6TXoxbE0vKzJUaVBwS1JIQ0Fm
        YTQvMnZGaXRpUkRDNDJrVWZBKzk5RWsKLS0tIGRKa1dJTHBKaGhFeldpZEkvRDl1
        bjQ5Y3BxMFBySUs4NkZaVjNvTVBlNTQKXvKdwqkRxFYS8qM9uvbUlsjZHbZHWNFJ
        jUiEsKtTK2526zzmcxUuDcEH6NA8XW0vXqLLBUk1CciX4CgRXnqnrQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ctpw7mxxzshknqmtwfn9c202hx0j57tv29fdsx4hym6hm5ed2stqtft3he
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-11T18:17:22Z"
  mac: ENC[AES256_GCM,data:g8myqhy3OPLCXBpwqIA9hlE+cfElOLOWP26aM9BurLz3G4XzJVyQlhzSuT+Ud0rMYyVNGo/AH/zXcmfjXYAKIySMuXKIxzDZ1Ubl6wmsBUZmz+ESTNgslMqWsBIVykaNlr6TwxdBGbmoKasmCyYgLs7T0TQKd6vuviaD9PBOuvc=,iv:KBQY6QtBaCnCYFDfwfM4ZM70iGNyHWPkcYnyYVtwPUw=,tag:+cgRIn/4gwJAkLxHmSXnOw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
